<a href="https://colab.research.google.com/github/KalpanadeviGunasekaran/Neural-Network/blob/main/NeuralNetwork_from_stratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [3]:
y=np.array(([1],[0],[1]))
y

array([[1],
       [0],
       [1]])

In [5]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [6]:
def derivative_sigmoid(x):
  return x*(1-x)

In [7]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [8]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [9]:
for i in range(epoch):
    # Forward Propagation
    # Hidden Layer
    hidden_layer_input = np.dot(x, wh) + bh
    hidden_layer_activation = sigmoid(hidden_layer_input)
    # Output Layer
    output_layer_input = np.dot(hidden_layer_activation, wo) + bo
    predicted_output = sigmoid(output_layer_input)
    # Backward Propagation
    # Calculate Error
    error = y - predicted_output
    # Calculate gradients at output layer
    slope_output_layer = derivative_sigmoid(predicted_output)
    delta_output = error * slope_output_layer
    # Calculate gradients at hidden layer
    error_hidden_layer = delta_output.dot(wo.T)
    slope_hidden_layer = derivative_sigmoid(hidden_layer_activation)
    delta_hidden = error_hidden_layer * slope_hidden_layer
    # Update Weights and Biases
    wo += hidden_layer_activation.T.dot(delta_output) * lr
    bo += np.sum(delta_output, axis=0, keepdims=True) * lr
    wh += x.T.dot(delta_hidden) * lr
    bh += np.sum(delta_hidden, axis=0, keepdims=True) * lr


In [10]:
predicted_output

array([[0.94950119],
       [0.06939992],
       [0.95917018]])